apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: n8n-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "67219d50-5eae-4151-8abc-80b947d4bb94"
    keyvaultName: "kv-n8n-mercury"
    tenantId: "3643c16e-9664-43e1-a80f-99e34ade6695"
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
  secretObjects:
    - secretName: n8n-container-env
      type: Opaque
      data:
        - objectName: db-user
          key: DB_POSTGRESDB_USER
        - objectName: db-password
          key: DB_POSTGRESDB_PASSWORD
